// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {potion} from '../models';
import {vision} from '../models';
import {petfeed} from '../models';

export function CalibratePotions(arg1:number,arg2:potion.CalibSpec):Promise<potion.CalibrationView>;

export function IsElevated():Promise<boolean>;

export function ListWindows():Promise<Array<vision.WindowInfo>>;

export function LoadPotionCalibration():Promise<potion.CalibrationView>;

export function NextFrame(arg1:number):Promise<vision.FramePayload>;

export function PetFeedStatus():Promise<petfeed.Status>;

export function PotionStatus():Promise<potion.Status>;

export function RestartAsAdmin():Promise<void>;

export function StartCapture(arg1:number,arg2:vision.Options):Promise<void>;

export function StartPetFeed(arg1:number,arg2:number,arg3:string):Promise<void>;

export function StartPotionWatch(arg1:number,arg2:potion.WatchOptions):Promise<void>;

export function StopCapture():Promise<void>;

export function StopPetFeed():Promise<void>;

export function StopPotionWatch():Promise<void>;

export function TeachPotionDigits(arg1:number,arg2:number,arg3:number):Promise<potion.CalibrationView>;

export function UpdateOptions(arg1:vision.Options):Promise<void>;
