// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalibratePotions(arg1, arg2) {
  return window['go']['main']['App']['CalibratePotions'](arg1, arg2);
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function ListWindows() {
  return window['go']['main']['App']['ListWindows']();
}

export function LoadPotionCalibration() {
  return window['go']['main']['App']['LoadPotionCalibration']();
}

export function NextFrame(arg1) {
  return window['go']['main']['App']['NextFrame'](arg1);
}

export function PetFeedStatus() {
  return window['go']['main']['App']['PetFeedStatus']();
}

export function PotionStatus() {
  return window['go']['main']['App']['PotionStatus']();
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function StartCapture(arg1, arg2) {
  return window['go']['main']['App']['StartCapture'](arg1, arg2);
}

export function StartPetFeed(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartPetFeed'](arg1, arg2, arg3);
}

export function StartPotionWatch(arg1, arg2) {
  return window['go']['main']['App']['StartPotionWatch'](arg1, arg2);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}

export function StopPetFeed() {
  return window['go']['main']['App']['StopPetFeed']();
}

export function StopPotionWatch() {
  return window['go']['main']['App']['StopPotionWatch']();
}

export function TeachPotionDigits(arg1, arg2, arg3) {
  return window['go']['main']['App']['TeachPotionDigits'](arg1, arg2, arg3);
}

export function UpdateOptions(arg1) {
  return window['go']['main']['App']['UpdateOptions'](arg1);
}
